[build]
  base = "/"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

# 前端路由重定向設置
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 後端 API 代理設置 (如果您的後端已部署到其他地方)
[[redirects]]
  from = "/api/*"
  to = "https://liyulaw-api.herokuapp.com/:splat"  # 請替換為您實際的後端 API 地址
  status = 200
  force = true

# 啟用 HTTPS 和安全標頭
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' https://liyulaw-api.herokuapp.com;"
